import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import actividadesRouter from "./actividades";
import eventosRouter from "./eventos";
import fiestasRouter from "./fiestas";
import excursionesRouter from "./excursiones";
import viajesRouter from "./viajes";
import noticiasRouter from "./noticias";
import serviciosRouter from "./servicios";
import sociosRouter from "./socios";
import gruposRouter from "./grupos";
import delegadoRouter from "./delegado";
import inscripcionesRouter from "./inscripciones";
import sugerenciasRouter from "./sugerencias";
import propuestasJuntaRouter from "./propuestasJunta";
import convocatoriasRouter from "./convocatorias";
import actasRouter from "./actas";
import expedientesRouter from "./expedientes";
import subvencionesRouter from "./subvenciones";
import contactoRouter from "./contacto";
import pagosRouter from "./pagos";
import syncRouter from "./sync";
import configRouter from "./config";
import adminRouter from "./admin";
import pulunpesRouter from "./pulunpes";
import hojasRouter from "./hojas";
import articulosRouter from "./articulos";
import galeriaRouter from "./galeria";
import nosotrosRouter from "./nosotros";
import perfilRouter from "./perfil";
import asociacionRouter from "./asociacion";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(actividadesRouter);
router.use(eventosRouter);
router.use(fiestasRouter);
router.use(excursionesRouter);
router.use(viajesRouter);
router.use(noticiasRouter);
router.use(serviciosRouter);
router.use(gruposRouter);
router.use(delegadoRouter);
router.use(sociosRouter);
router.use(inscripcionesRouter);
router.use(sugerenciasRouter);
router.use(propuestasJuntaRouter);
router.use(convocatoriasRouter);
router.use(actasRouter);
router.use(expedientesRouter);
router.use(subvencionesRouter);
router.use(contactoRouter);
router.use(pagosRouter);
router.use(syncRouter);
router.use(configRouter);
router.use(adminRouter);
router.use(pulunpesRouter);
router.use(hojasRouter);
router.use(articulosRouter);
router.use(galeriaRouter);
router.use(nosotrosRouter);
router.use(perfilRouter);
router.use(asociacionRouter);

export default router;
